### PR TITLE
Update manifest, gupdate, and icons

### PR DESCRIPTION
**Pull request by Alex313031**
also added more sizes and changed the filenames to reflect "best practices" for icons in chromium extensions.

### CODE REVIEW

**Comment by kkkrist** [comment]
Thank you for the PR, it's much appreciated! Do you think the changes justify an update? I don't think many users will notice the new logo, especially given the size the logo is displayed on the top bar. I'd rather only publish updates with functional changes in order to not confuse users.

**Comment by Alex313031** [comment]
Well, I also updated the manifest. I believe that any change that more than a single file warrants a new minor version, once it is finalized. You could selectively merge and keep the previous version number, but when I publish it I will use the new version, because the semantic versioning decisions I make with all my projects are like this. I work on something, then When I am done with whatever it is, and I know it will all be one finalized commit for the day, I take a look at what has changed. If I changed a single line in a file, or renamed a single file, maybe not. But modifying multiple files, as well as the names and the look of the application seems like a reasonable reason to make a minor version bump. If a user is that concerned that the minor version bump caused a change of behavior (which it wouldn't), they would likely be adept enough to look here in the commits or release notes for a given release.

Thats just my two cents, but you are the master of this repo and do what you think is best.

**Comment by kkkrist** [comment]
I have cherry picked the icon changes from your fork and think I'll wait for the next substantial change to release a new version. Thank you again!

(I prefer semantic versioning for my projects, so changes not affecting the end user will not trigger a new version, patch versions are for fixes, minor version for new features and major versions for breaking changes)

**Comment by kkkrist** [comment]
Also, if you publish your fork to the store, please make a proper fork out of it so that it's distinguishable from my version (adding something to the name or changing it, inserting yourself as the author into the manifest, maybe starting over with the version number at 1.0.0, adding a fork notice to the README). Thank you!

**Pull request closed without merging**
